### ISSUE TITLE
A new clang-format style

### ISSUE THREAD

**Issue by ikspress** [cppfastio/fast_io#875]
```yaml
AccessModifierOffset: -4
AlignArrayOfStructures: Right
AlignConsecutiveBitFields: Consecutive
AlignConsecutiveMacros: Consecutive
AllowShortBlocksOnASingleLine: Empty
AllowShortFunctionsOnASingleLine: Empty
AlwaysBreakTemplateDeclarations: Yes
BasedOnStyle: LLVM
BreakBeforeTernaryOperators: false
BreakConstructorInitializers: AfterColon
BreakInheritanceList: AfterColon
IndentPPDirectives: AfterHash
IndentWidth: 4
KeepEmptyLinesAtTheStartOfBlocks: false
PackConstructorInitializers: CurrentLine
QualifierAlignment: Right
RemoveBracesLLVM: true
RemoveParentheses: ReturnStatement
RemoveSemicolon: true
ShortNamespaceLines: 0
SortIncludes: CaseSensitive

AttributeMacros:
  - CPPLAB_ATTRIB_forceinline
  - CPPLAB_ATTRIB_may_alias
  - NTSYSAPI
  - NTSYSCALLAPI
  - WINADVAPI

StatementMacros:
  - _Pragma # llvm/llvm-project#54180
```

这个是我目前在用的 .clang-format 格式，与本项目有较大区别

1. 我使用空格作为缩进，而不是制表符
2. 我的花括号不是独占一行
3. 尽量少的花括号
4. 限定到一行 80 字符

124条我认为可以调整，fast_io 的代码格式似乎不大好
